### PR TITLE
Q&A

### PR DESCRIPTION
**Pull request by achaikou**
3 sections that I felt are missing from documentation and which I myself would like to see as a user.

- Section for people who landed up on this project page but are totally clueless about what's going on and need to figure out if they should investigate dlisio further.
- Section for people who received one of our errors and are actually at loss with regards to what they should do about it. (aka the most common situation that I saw which lead to the provided error)
- Section for some future dlisio developers. Most likely no-one ever will find it useful, but as I already acquired some dlis debugging mindset, it probably makes sense to share it.

Feel free to completely annihilate small/big/~all~ parts of this PR. Mark everything that seems unclear on first read, it will likely be the same for users.

### CODE REVIEW

**Comment by ErlendHaa** [comment]
Closes #102

**Comment by achaikou** [comment]
To be updated some undefined time in the future:
- Move "Can I be sure that dlisio presents me the data correctly?" section to Readme
- Remove everything else from Q&A, thus dropping explanations for clueless repo viewers
- Add Errors explanation section under dlis, while removing everything that doesn't correspond to literal error string (aka performance messages).
- (Check that messages still make sense)
- Put investigation guide in the docs, but never link it publicly.

**Comment by lucasblanes** [comment]
Hello! I don't know if this is the best place to ask, but can I create DLIS files using DLISio?

**Comment by achaikou** [comment]
Hi @lucasblanes !

No, this is a place for proposed changes to the code. But I see why the title caused confusion :)
Better place to ask questions is [Issues](https://github.com/equinor/dlisio/issues) as it can be searched by others wondering the same.

To the question itself:
no, dlisio can't write dlis files. At the moment there are no plans to support it in any foreseeable future.

**Comment by lucasblanes** [comment]
Hello @achaikou ! Sorry for the confusion and thank you for your answer!

**Pull request closed without merging**
